/**
 * CarbonLens — MongoDB Emission Factors Import Script
 *
 * Reads emission_factors.json and global_benchmarks.json from ../data/
 * and outputs MongoDB-compatible insert commands.
 *
 * Usage:
 *   node scripts/import-factors.js
 *
 * This script generates the mongo shell / mongosh commands needed to populate
 * the emission_factors and global_benchmarks collections in MongoDB Atlas.
 * The actual insertion can be done via:
 *   - MongoDB Atlas Data Explorer (copy/paste)
 *   - mongosh connection
 *   - The Agent's own MCP insert-many tool
 *
 * The Agent will also be able to insert these directly via MCP tools,
 * so this script also validates the JSON data structure.
 */

const fs = require("fs");
const path = require("path");

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const DATA_DIR = path.resolve(__dirname, "..", "data");
const FACTORS_FILE = path.join(DATA_DIR, "emission_factors.json");
const BENCHMARKS_FILE = path.join(DATA_DIR, "global_benchmarks.json");

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/**
 * Validate an emission factor entry has all required fields.
 * @param {object} entry
 * @param {number} index
 * @returns {string[]} List of validation errors
 */
function validateFactorEntry(entry, index) {
  const errors = [];
  if (!entry.activity || typeof entry.activity !== "string") {
    errors.push(`Entry ${index}: missing or invalid "activity"`);
  }
  if (!entry.category || typeof entry.category !== "string") {
    errors.push(`Entry ${index}: missing or invalid "category"`);
  }
  if (!entry.unit || typeof entry.unit !== "string") {
    errors.push(`Entry ${index}: missing or invalid "unit"`);
  }
  if (typeof entry.factor_kg_co2e !== "number") {
    errors.push(`Entry ${index}: missing or invalid "factor_kg_co2e"`);
  }
  if (!entry.source || typeof entry.source !== "string") {
    errors.push(`Entry ${index}: missing or invalid "source"`);
  }
  const validConfidence = ["High", "Medium", "Low"];
  if (!validConfidence.includes(entry.confidence)) {
    errors.push(`Entry ${index}: "confidence" must be one of ${validConfidence.join(", ")}`);
  }
  return errors;
}

/**
 * Validate a benchmark entry.
 * @param {object} entry
 * @param {number} index
 * @returns {string[]}
 */
function validateBenchmarkEntry(entry, index) {
  const errors = [];
  if (!entry.country || typeof entry.country !== "string") {
    errors.push(`Benchmark ${index}: missing or invalid "country"`);
  }
  if (typeof entry.daily_kg_co2e !== "number" || entry.daily_kg_co2e < 0) {
    errors.push(`Benchmark ${index}: missing or invalid "daily_kg_co2e"`);
  }
  return errors;
}

// ---------------------------------------------------------------------------
// Report Generation
// ---------------------------------------------------------------------------

/**
 * Generate a summary report of the imported data.
 * @param {object[]} factors
 * @param {object[]} benchmarks
 */
function generateReport(factors, benchmarks) {
  console.log("\n" + "=".repeat(60));
  console.log("  CarbonLens — Emission Factors Import Report");
  console.log("=".repeat(60));

  // Category breakdown
  const categories = {};
  for (const f of factors) {
    categories[f.category] = (categories[f.category] || 0) + 1;
  }

  console.log(`\nTotal emission factors: ${factors.length}`);
  console.log("\nBy category:");
  for (const [cat, count] of Object.entries(categories)) {
    console.log(`  ${cat}: ${count} entries`);
  }

  console.log(`\nTotal benchmarks: ${benchmarks.length}`);
  console.log("\nCountries:");
  for (const b of benchmarks) {
    console.log(`  ${b.country} (${b.country_code}): ${b.daily_kg_co2e} kg CO₂e/day`);
  }

  // Confidence distribution
  const confidence = {};
  for (const f of factors) {
    confidence[f.confidence] = (confidence[f.confidence] || 0) + 1;
  }
  console.log("\nConfidence distribution:");
  for (const [level, count] of Object.entries(confidence)) {
    console.log(`  ${level}: ${count} entries`);
  }
}

// ---------------------------------------------------------------------------
// MongoDB Commands Generator
// ---------------------------------------------------------------------------

/**
 * Generate mongosh-compatible insert commands.
 * @param {object[]} factors
 * @param {object[]} benchmarks
 * @returns {string}
 */
function generateMongoCommands(factors, benchmarks) {
  const lines = [];

  lines.push("// CarbonLens — MongoDB Data Import");
  lines.push("// Generated by scripts/import-factors.js");
  lines.push("// Run with: mongosh <connection-string>");
  lines.push("");
  lines.push(`use carbonlens;`);
  lines.push("");

  // Emission factors
  lines.push("// === emission_factors ===");
  lines.push("db.emission_factors.drop();");
  lines.push("");
  lines.push("db.emission_factors.insertMany([");
  for (let i = 0; i < factors.length; i++) {
    const f = factors[i];
    const comma = i < factors.length - 1 ? "," : "";
    lines.push(`  ${JSON.stringify(f)}${comma}`);
  }
  lines.push("]);");
  lines.push("");

  // Create index on emission_factors
  lines.push("db.emission_factors.createIndex({ category: 1 });");
  lines.push("db.emission_factors.createIndex({ activity: 1 }, { unique: true });");
  lines.push("");

  // Global benchmarks
  lines.push("// === global_benchmarks ===");
  lines.push("db.global_benchmarks.drop();");
  lines.push("");
  lines.push("db.global_benchmarks.insertMany([");
  for (let i = 0; i < benchmarks.length; i++) {
    const b = benchmarks[i];
    const comma = i < benchmarks.length - 1 ? "," : "";
    lines.push(`  ${JSON.stringify(b)}${comma}`);
  }
  lines.push("]);");
  lines.push("");

  // Create index on global_benchmarks
  lines.push("db.global_benchmarks.createIndex({ country_code: 1 }, { unique: true });");
  lines.push("");

  lines.push("// Verify imports");
  lines.push(`db.emission_factors.countDocuments(); // Expected: ${factors.length}`);
  lines.push(`db.global_benchmarks.countDocuments();  // Expected: ${benchmarks.length}`);
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  console.log("CarbonLens — Emission Factors Import Script");
  console.log("Data directory:", DATA_DIR);

  // Read and parse JSON files
  let factors;
  try {
    const raw = fs.readFileSync(FACTORS_FILE, "utf-8");
    factors = JSON.parse(raw);
    console.log(`\n✓ Read ${factors.length} emission factors`);
  } catch (err) {
    console.error(`✗ Failed to read ${FACTORS_FILE}:`, err.message);
    process.exit(1);
  }

  let benchmarks;
  try {
    const raw = fs.readFileSync(BENCHMARKS_FILE, "utf-8");
    benchmarks = JSON.parse(raw);
    console.log(`✓ Read ${benchmarks.length} benchmarks`);
  } catch (err) {
    console.error(`✗ Failed to read ${BENCHMARKS_FILE}:`, err.message);
    process.exit(1);
  }

  // Validate data
  let allErrors = [];
  factors.forEach((entry, i) => {
    allErrors = allErrors.concat(validateFactorEntry(entry, i));
  });
  benchmarks.forEach((entry, i) => {
    allErrors = allErrors.concat(validateBenchmarkEntry(entry, i));
  });

  if (allErrors.length > 0) {
    console.error(`\n✗ Validation FAILED — ${allErrors.length} error(s):`);
    allErrors.forEach((err) => console.error(`  - ${err}`));
    process.exit(1);
  }
  console.log("✓ All data validated");

  // Generate report
  generateReport(factors, benchmarks);

  // Generate MongoDB commands
  const mongoCommands = generateMongoCommands(factors, benchmarks);
  const outputFile = path.join(DATA_DIR, "..", "scripts", "import-commands.mongosh.js");
  fs.writeFileSync(outputFile, mongoCommands, "utf-8");
  console.log(`\n✓ MongoDB commands written to: ${outputFile}`);

  console.log("\n" + "=".repeat(60));
  console.log("  Import Complete — Data is ready for MongoDB Atlas");
  console.log("=".repeat(60));
  console.log("\nNext steps:");
  console.log("  1. Copy import-commands.mongosh.js to MongoDB Atlas Data Explorer");
  console.log("  2. Or run: mongosh <your-atlas-uri> < scripts/import-commands.mongosh.js");
  console.log("  3. Or let the Agent import via MCP insert-many");
  console.log("  4. Verify with: db.emission_factors.countDocuments()");
}

main();
